Replies:
  SetAlready: '**âŒ You already setup Ticket in this server : **'
  SettTimer : '**âŒš 20 sec for Deleting this Message**'
  SetTFinsh : '**ğŸ”” Timer Finish**'
  OpenAlredy: '**ğŸ‘€ You already opened ticket :**'
  TicketOpnd: '**âœ… Your Ticket Opened Successfully :**'
  RoleAlreadyExists: "**ğŸ‘€ This Role already added to support**"
  RoleAdded: "**âœ… Role Support added Successfully ! :**"
  RoleNotFound: "**ğŸ™„ This role is not in the support list.**"
  RoleRemoved: "**âœ… The role has been removed from the support list:**"
  NoSupportRoles: "**ğŸ¤¨ There are no support roles set up yet.**"
  NoPermission: "**âŒ You don't have permission to use this button**"
  TicketClaimed: "**ğŸ™‹â€â™‚ï¸ This Ticket Claimed by [User]**"
  TicketUnclaimed: "**âŒ [User] Unclaimed this ticket**"
  NoUPermission: "**âŒ You do not have permission to use this command.**"
  NotATicket: "**ğŸ™„ This channel is not a ticket channel.**"
  UserNotInChannel: '**ğŸ™„ The specified user is not in this channel or does not have permissions.**'
  UserNoClaimed: '**ğŸ™„ You are not the one handling this ticket**'
  UserAlreadyInChannel: '**ğŸ™„ The specified user is already in this channel.**'
  ConfirmationMessage: '**ğŸ¤¨ Are You sure you want to close this ticket ?**'
  ConfirmationMessageD: '**ğŸ¤¨ Are You sure you want to delete this ticket ?**'
  CloseSuccess: '**âœ… The ticket has been closed successfully.**'
  CloseFaileds: '**ğŸš« Failed to close the ticket. No ticket data found.**'
  ClosedAlredy: '**ğŸ™„ This ticket is already closed.**'
  SetpNotFound: '**ğŸ‘€ Setup not found. Please configure the ticket system.**'
  TranscrReady: '**âœ… Here is your transcript file:**'
  TicketDelete: '**ğŸ—‘ï¸ This ticket delete after 5sec**'
  NoClaimClose: '**ğŸ¤¨ This Ticket is Closed, you cannot claim it.**'
  NUClaimClose: '**ğŸ¤¨ This Ticket is Closed, you cannot unclaim it.**'
  ReopenUucess: '**ğŸ”„ï¸ Your ticket has been reopened. Please check the channel:**'
  ReopenSucess: '**âœ… The ticket has been reopened successfully.**'
  StatusSelect: '**ğŸŒ Please select the ticket status you want to view:**'
  StatusNoSelc: '**ğŸ™„ You did not select any ticket status.**'
  StatusSelAll: '**â¡ï¸ Here are all the tickets:**'
  StatusSelOpn: '**â¡ï¸ Here are the open tickets:**'
  StatusSelCls: '**â¡ï¸ Here are the closed tickets:**'
